name: main

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox virtualenv

      - name: Test build
        run: tox

      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}
          coverage_path: ./coverage.xml
          test_framework: PYTEST
