name: release-drafter-ci

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

# This one automatically bumps the version
#      - name: Conventional Changelog Action
#        uses: TriPSs/conventional-changelog-action@v3
#        with:
#          github-token: ${{ secrets.github_token }}
#          skip-version-file: true

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: thing
          monorepo-tags: true
          path: app
          extra-files: |
            app/__init__.py
