name: upload-pypi-ci

#on:
#  release:
#    types: [ published ]

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'release-please**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
