name: upload-pypi-ci

on:
  push:
    branches:
      - main
#    types: [ published ]
#on:
#  pull_request_target:
#    types:
#      - closed
#    branches:
#      - 'release-please**'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: go
          extra-files: |
            go/global.go

  docker:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v2
