name: release-drafter-ci

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

# # Monorepo
#      - uses: google-github-actions/release-please-action@v3
#        with:
#          release-type: python
#          package-name: thing
#          monorepo-tags: true
#          path: app
#          extra-files: |
#            app/__init__.py

      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: python
#          release-as: v0.5.0
          extra-files: |
            app/__init__.py
        changelog-types: |
          [
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"provider","section":"Provider","hidden":false}
          ]


      - run: echo 1
        if: ${{ steps.release-please.outputs.release_created }}
